// Auto-generated by wrangler types — DO NOT EDIT MANUALLY
/// <reference types="@cloudflare/workers-types" />

interface Env {
  DB: D1Database;
  ADMIN_PASSWORD: string;
  ADMIN_JWT_SECRET: string;
  RESEND_API_KEY: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_REFRESH_TOKEN: string;
  GCAL_SANTANA: string;
  GCAL_TATUAPE: string;
  GCAL_LAPA: string;
  GCAL_SAO_MIGUEL: string;
  GCAL_GUARULHOS: string;
}
